name: Deploy Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@wis.wellspring.edu.vn << 'EOF'
          cd /srv/app/workspace-frontend

          echo "Pulling latest code..."
          git reset --hard
          git pull origin main

          echo "Installing dependencies..."
          npm install --legacy-peer-deps

          echo "Building Vite project..."
          npm run build

          echo "Restarting frontend with PM2..."
          pm2 restart wis-frontend || pm2 start "serve -s dist -l 3000" --name wis-frontend

          pm2 save
        EOF